version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant_aqua_rag
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage
    networks:
      - qdrant_network

networks:
  qdrant_network:
    driver: bridge

volumes:
  qdrant-storage:
    name: qdrant-storage
